# General info
title: "Moretto's Follies"
subtitle: ""
url: https://markmoretto.github.io
baseurl: /


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# markdown: redcarpet2
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  # syntax_highlighter_opts:
  #   block:
  #     line_numbers: true
# Sass/SCSS
sass:
  sass_dir: _sass
  #style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

paginate: 3

# Author info
author:
  name: "Mark Moretto"

# https://jekyllrb.com/docs/configuration/webrick/
webrick:
  headers:
    Accept: application/json
    Access-Control-Allow-Origin: http://127.0.0.1:4000
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
    Access-Control-Allow-Headers: Content-Type, Accept-Language, Content-Language
    
# GitHub repo for this site
github:
  repo: https://github.com/markmoretto/markmoretto.github.io

# Your UA tracking number (i.e 35858753-1) for Google Analytics.
# If you comment this out, or don't fill out this parameter - Google analytics won't be included.
googleID: 164816712-1

# Style of permalinks
permalink: pretty

# Variable format options for URL styles below
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-month:day-:year/:title.html/            => 04-29-2009/slap-chop.html
# /blog/:yearr/:month/:day/:title                 => /blog/2009/04/29/slap-chop/index.html

# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
#timezone: America/Detroit # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# # https://dubsman.gitlab.io/posts/gitlab-jekyll-npm.html
# # add bundle cache to 'vendor' for speeding up builds
# cache:
#   paths: 
#     - vendor/

# # https://dubsman.gitlab.io/posts/gitlab-jekyll-npm.html
# pages:
#   stage: deploy
#   script:
#     - bundle exec jekyll build -d public/
#   artifacts:
#     paths:
#       - public
#   only:
#     - master  # this job will affect only the 'master' branch


# Plugins (Formerly known as 'gems' -> https://github.com/elixir-lang/elixir-lang.github.com/issues/1035)
plugins:
  # - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-default-layout
  # - jekyll-github-metadata
  # - jekyll-include-cache



defaults:
  - scope:
      path: ""
      path: "posts"
    values:
      layout: "posts"  
  - scope:
      path: ""
    values:
      layout: "default"


include: [node_modules]

# Included `node_modules/lit-html/CHANGELOG.md` since bundle/liquid has a fit when dealing with '[{{}}]'
exclude: [Rakefile, CNAME, README.md, .gitignore, package-lock.json, node_modules/lit-html/CHANGELOG.md]



